config/routes.rb
Rails.application.routes.draw do  #L05
    resources :users
    resources :tweets
    resources :likes
    
    
    root 'users#index'
    
    post 'users/delete'
    
    post 'top/login'
    get  'top/logout'
    get  'top/login'
    get '/new_tweet_path', to:'tweets#new'
    get 'top/main'
    get 'likes/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :like_tweets,through: :likes, source: :tweet
    has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    def index
     @tweets = Tweet.all
     @users = User.all
    end
    
    def create
          @tweets = Tweet.all
     tweet = Tweet.find(params[:tweet_id])
     user = User.find_by(uid: session[:login_uid])
     user.like_tweets << tweet
     render 'top/main'
    end
    
    def destroy
               @tweets = Tweet.all
     tweet = Tweet.find(params[:id])
     user = User.find_by(uid: session[:login_uid])
     tweet.likes.find_by(user_id: user.id).destroy
     render 'top/main'
    end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController


 def main
      if session[:login_uid] != nil
        flash[:notice] = "ログインに成功しました"
        render'top/main'    
      else
        session[:login_uid] = nil
        flash[:notice] = "ログインに失敗しました"
        render'login'
      end
 end
  
 def login

    @tweets = Tweet.all
     if user = User.find_by_uid(params[:uid])
             if params[:uid] == user.uid && BCrypt::Password.new(user.pass) == params[:pass]
               session[:login_uid] = user.uid
               render 'top/main'
             else
               render 'error'
             end
     end
 end
 
 def logout
  session[:login_uid] = nil
  redirect_to '/'
 end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    
def index
    @tweets = Tweet.all
    @users = User.all
end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweets = Tweet.all
    user = User.find_by(uid: session[:login_uid])
    message= params[:tweet][:message]
    @tweet = Tweet.new(message: message,user_id:user.id)
    if @tweet.save
      render 'top/main'  
    else
      render 'new'
    end
  end
  
  def destroy
   @tweets = Tweet.all
    tweet = Tweet.find(params[:id])
    tweet.destroy
    render 'top/main'  
  end
  
  def show
    @tweet = Tweet.find(params[:id])
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    message= params[:tweet][:message]
    @tweet = Tweet.find(params[:id])
    @tweet.update(message: message)
    if @tweet.save
      flash[:notice] = "1 record update"
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
def index
    @tweets = Tweet.all
    @users = User.all
end

def new
    @user = User.new
end

def create
    uid= params[:user][:uid]
    pass = params[:user][:pass]
    age = params[:user][:age]
    signup_password = BCrypt::Password.create(pass)
    @user = User.new(uid: uid, pass: signup_password,age: age)
    if @user.save
        flash[:notice] = "アカウント作成に成功しました"
      redirect_to '/'
    else
      render 'top#login'
    end
end

def destroy
    @user = User.find(params[:uid])
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    render'users/index'
end



    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp1</title>
    <%= csrf_meta_tags %>
        <meta charset="utf-8">
        <body bgcolor=#EEEEEE>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
    <div id="container">
        <div id="header">
            <%= render "tweets/header" %>
        </div>
        <div id="sidebar">
            <%= render "tweets/sidebar" %>
        </div>
        <div id="content">
            <%= yield %>
        </div>
        <div id="footer">
            <%= render "tweets/footer" %>
        </div>
    </div>
</body>
</html>

app/views/top/error.html.erb
<p>ログインに失敗しました</p>
<%= link_to '戻る', '/' %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post do %>
 <%= label_tag :uid, 'ユーザーID' %>
 <%= text_field_tag :uid %>
 <%= label_tag :pass, 'パスワード' %>
 <%= password_field_tag :pass %>
 <%= submit_tag 'ログイン' %>
 <br><br>
<% end %>
 <%= link_to 'Back', '/' %>

app/views/top/main.html.erb
<h2>ツイート</h2>
<hr>
<br>

<% @tweets.each do |e| %>
<p>
    <br>
   <%= e.message%>&nbsp;&nbsp;
    <%= link_to 'いいね', likes_path(tweet_id: e.id), method: :post %>
    <%= link_to 'いいね削除', like_path(e), method: :delete %>
    <br>
</p>
<% end %>
<hr>
<br><a href= '../tweets/new' class="btn-gradient-flat"><u>ツイート</u></a><br>
<%= link_to 'ログアウト', '../top/logout' %>
<br>

app/views/tweets/_form.html.erb
<%= f.label :message, 'メッセージ' %>
<%= f.text_field :message %>

<%= f.submit 'ツイートする' %>

app/views/tweets/_header.html.erb
<img src="assets/b.png" alt="header" height="140" width="100%" align="top">

app/views/tweets/_sidebar.html.erb
<p class="trim-image-to-circle"></p>
<h1><%= "#{session[:login_uid]}"%></h1>
<b><%= "@#{session[:login_uid]}"%></b>
<p>test</p>
<br>
<p>福岡県</p>

app/views/tweets/edit.html.erb
<%= form_for @tweet , name: {action: :update} do |f| %>
<%= render "form", f:f%>
<% end %>

<p><%= link_to 'Back', root_path %></p>

app/views/tweets/index.html.erb
<h2>ツイート</h2>
<hr>
<br>
<% @tweets.each do |tweet| %>
<p>
    <br>
   <%= tweet.message%>&nbsp;&nbsp;
    <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
    <%= link_to '表示', tweet_path(tweet.id) %>
    <%= link_to '編集', edit_tweet_path(tweet.id) %>
    <br>
</p>
<hr>

<% end %>
<p><%= link_to 'ツイート', new_tweet_path %></p>

app/views/tweets/new.html.erb
<%= form_for @tweet , name: {action: :create} do |f| %>
<%= f.label :message, 'メッセージ' %>
<%= f.text_field :message %>

<%= f.submit 'ツイートする' %>
<% end %>

<p><%= link_to 'Back', root_path %></p>

app/views/tweets/show.html.erb
<p>
    <strong>message：</strong>
    <%= @tweet.message %>
</p>

<p>
    <strong>tdate:</strong>
    <%= @tweet.tdate %>
</p>

<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<%= link_to 'アカウント作成', 'users/new' %>
<%= link_to 'ログイン','top/login' %>
<br><br><br>
<h2>ツイート</h2>
<hr>
<br>
<% @tweets.each do |e| %>
<p>
    <br>
   <%= e.message%>&nbsp;&nbsp;
    <br>
</p>
<% end %>

app/views/users/new.html.erb
<%= form_for @user , url: {action: :create} do |f| %>
 <%= f.label :uid, 'ユーザーID' %>
 <%= f.text_field :uid %>
 <%= f.label :pass, 'パスワード' %>
 <%= f.password_field :pass %>
 <%= f.label :age, '年齢' %>
 <%= f.text_field :age %>
 <%= f.submit '登録' %>
<% end %>

 <%= link_to 'Back', '/' %>